name: Solar System Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'chinna_workflow'
env:
    MONGO_URL: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
    MONGO_USERNAME: $ {{vars.MONGO_USERNAME}}
    MONGO_PASSWORD: $ {{secrets.MONGO_PASSWORD}}    
jobs:
    unit-testing:
        name: Unit Testing
        strategy:
           matrix:
              NodeJS_version: [20,20.8,24]
              OS: [ubuntu-latest]
              exclude:
                - NodeJS_version: 19
                  os: ubuntu_latest


        runs-on: ${{ matrix.OS }}
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v6

        - name: Setup NodeJS Version
          uses: actions/setup-node@v6
          with:
            node-version: ${{ matrix.NodeJS_version }}
    
        - name: Install Dependencies
          run: npm install
    
        - name: Unit Testing
          run: npm test
          
        - name: Archive Test Result
          uses: actions/upload-artifact@v4
          with:
            name: Mocha-Test-Result
            path: test-results.xml